---
title: "2021traindata"
author: "Munerah Alfayez"
date: "2023-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages
library(ggrepel)
library(caret)
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
```



```{r}
df2021 <- read.csv("C:/Users/mnooo/OneDrive/سطح المكتب/work/training programs 2021Copy.csv",sep = ",",fileEncoding = "UTF-8")
```

```{r}
head(df2021)
```

```{r}
#replace null values with median in evaluation 
df2021 <- df2021 %>% mutate(across(evaluation, ~replace_na(., median(., na.rm=TRUE))))
```

```{r}
## add month colmn from the start date 
df2021$month <- format(as.Date(df2021$startdate, format="%d/%m/%Y"),"%m")
#convert to date 
df2021$month <- as.Date(anydate(df2021$month),format="%b")
```

```{r}
df2021 %>% group_by(month) %>%
summarise(registered = sum(registered))%>%arrange(., month) -> tt
```

```{r}
tt %>%
   tail(12) %>%
  ggplot( aes(x=month, y=registered)) +
    geom_line() +
    geom_point()+
 theme(panel.grid.minor.x=element_blank(),
           panel.grid.major.x=element_blank())+
 theme(panel.grid.minor.y=element_blank(),
           panel.grid.major.y=element_blank()) +
    scale_x_date(date_labels = "%b" ,breaks = unique(df2021$month))+
    xlab("Months") +
    ylab("student registered")+
    ggtitle("Number of students registered 2021")

```


```{r}

```

```{r}

```

